# Numpy exercises

Difference between numpy and arrays

In [52]:
from time import time
import numpy as np
from tqdm import tqdm 
##tried to import tqdm and time to estimate time of operation, the verobisty is low however if anybody knows how to show more detailed time please let me know

t1 = time()
a =[2,3,4,8,8,8]
b=[4,5,6,1,2,5]
c=[]
for i in tqdm(range(len(a))):
    c.append(a[i]*b[i])
t2 = time()
print(c)


100%|████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<?, ?it/s]

[8, 15, 24, 8, 16, 40]


In [53]:
a_arr = np.array(a) ## changing it into an array
b_arr = np.array(b)
c_arr = a_arr*b_arr ## array multiplication
print(c_arr)

[ 8 15 24  8 16 40]


Operations on nparray

In [54]:
print(c_arr.ndim) ## how many axis you have, here only 1-D vector so == 1 
print(c_arr.size) ## how many elements in total
print(c_arr.shape) ## tells you what is the shape of the data in terms of a tuple, here as you can see only six elements
print(c_arr.dtype) ## tells you what specific data type you are working with
print(c_arr.itemsize) ## tells you the specific byte size of one tem in the array
print(c_arr.data) ## kind of not useful (at least for me), let me know if this is useful somehow

1
6
(6,)
int32
4


Array creation

In [73]:
print(np.zeros((4,4))) ## zeros 4x4
print('----')
print(np.ones((4,4))) ## ones 4x4
print('----')
print(np.eye((4))) ## identity 4x4 (only works for aquare matrices (duh!))
print('----')
print(np.arange(1,50,10)) ## from to with a step (not including to btw)
print('----')
print(np.empty((4,4))) ## idk about this for sure, but it supposed to be random ints???
print('----')
print(np.linspace(1,6,num=10)) ##  from to (including to) but with equal spacing YOU decide
print('----')
print(np.zeros_like(c_arr)) ## zeros/ones/empty as one array you worked before, good for images and so on ...



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----
[ 1 11 21 31 41]
----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----
[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]
----
[0 0 0 0 0 0]
